# Generated by Django 5.2 on 2025-04-24 07:40

import django.db.models.deletion
import social.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_follow"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "media",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=social.models.post_media_file_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="social.profile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
